//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleClaim
    {
        public int ID { get; set; }
        public string ClaimNumber { get; set; }
        public string VehicleRegistionNumber { get; set; }
    }
}
